#!/bin/bash
echo "🚀 Deploying Summer's Phone System to Vercel..."
echo ""
echo "=== STEP 1: Deploy Database to Supabase ==="
echo ""
echo "Run this command to deploy the schema:"
echo ""
echo "npx supabase db push --db-url \"postgresql://postgres:YOUR_PASSWORD@db.xgcmbxcwdddcaxbqncdz.supabase.co:5432/postgres\""
echo ""
echo "Press Enter when ready for Step 2..."
read

echo ""
echo "=== STEP 2: Deploy to Vercel ==="
echo ""
echo "Run: vercel --prod"
echo ""
echo "When prompted for Environment Variables, enter:"
echo ""
echo "NEXT_PUBLIC_SUPABASE_URL=https://xgcmbxcwdddcaxbqncdz.supabase.co"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_EU_TbhfiOXKNbfE-DCzFoQ_sALsG_ZR"
echo "SUPABASE_SERVICE_ROLE_KEY= [GET FROM SUPABASE DASHBOARD → API → service_role]"
echo "TWILIO_ACCOUNT_SID=your_twilio_account_sid_here"
echo "TWILIO_AUTH_TOKEN=your_twilio_auth_token_here"
echo "TWILIO_PHONE_NUMBER=your_twilio_phone_number_here"
echo "OPENAI_API_KEY=your_openai_api_key_here"
echo "OPENCLAW_GATEWAY_URL=http://localhost:18789"
echo "OPENCLAW_GATEWAY_TOKEN=06273a2e90ea1215a4e93e986e72b71514092100545b393a"
echo ""
echo "Press Enter when ready for Step 3..."
read

echo ""
echo "=== STEP 3: Configure Twilio Webhook ==="
echo ""
echo "1. Go to: https://console.twilio.com/"
echo "2. Phone Numbers → Manage → Active Numbers → your_twilio_phone_number_here"
echo "3. Messaging Configuration:"
echo "   Webhook URL: https://YOUR-VERCEL-URL/api/webhooks/twilio/sms"
echo "   HTTP Method: POST"
echo "   Webhook signature validation: ENABLED"
echo ""
echo "4. Save configuration"
echo ""
echo "Press Enter when ready for Step 4..."
read

echo ""
echo "=== STEP 4: Test It! ==="
echo ""
echo "1. From your phone (+19493951074), text:"
echo "   TO: +18449023577"
echo "   MESSAGE: Hey Summer, are you there?"
echo ""
echo "2. You should get an AI response within seconds!"
echo ""
echo "3. Check dashboard: https://YOUR-VERCEL-URL/conversations"
echo ""
echo "🎉 Done!"